---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2026/3/27 下午4:54
---
---
---复用与聚合消费者一致的原子计数折叠脚本
local cntKey = KEYS[1]           -- Redis 的键名，如 "cnt:post:123"
local schemaLen = tonumber(ARGV[1])  -- Schema 长度=5（支持 5 个指标），表示支持 5 个计数指标（点赞、收藏、评论、分享、浏览）
local fieldSize = tonumber(ARGV[2])  -- 每个字段大小=4 字节，每个指标占用 4 个字节（可以存储 0~42 亿的数值）
local idx = tonumber(ARGV[3])        -- 字段索引：1=点赞，2=收藏
local delta = tonumber(ARGV[4])      -- 变化量：+1 或 -1

local function read32be(s, off)
    local b = {string.byte(s, off+1, off+4)}
    local n = 0
    for i=1,4 do n = n * 256 + b[i] end
    return n
end

local function write32be(n)
    local t = {}
    for i=4,1,-1 do t[i] = n % 256; n = math.floor(n/256) end
    return string.char(unpack(t))
end

local cnt = redis.call('GET', cntKey)  --读取当前计数值
if not cnt then cnt = string.rep(string.char(0), schemaLen * fieldSize) end   --如果键不存在，创建 20 字节的全零字符串，，计算：schemaLen * fieldSize = 5 * 4 = 20 字节
local off = (idx-1) * fieldSize  --计算点赞字段的字节偏移量，off = 1（点赞） * 4 = 4
local v = read32be(cnt, off) + delta   --read32be(cnt, 1) 读取从第4个开始的后 4 个字节：\x00\x00\x03\xE8
if v < 0 then v = 0 end
local seg = write32be(v)
cnt = string.sub(cnt, 1, off) .. seg .. string.sub(cnt, off+fieldSize+1)
redis.call('SET', cntKey, cnt)
return 1
