---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2026/3/1 下午5:33
---
local bmKey = KEYS[1]
local offset = tonumber(ARGV[1])
local op = ARGV[2] -- 'add' or 'remove'
local prev = redis.call('GETBIT', bmKey, offset)
if op == 'add' then
    if prev == 1 then
        return 0
    end
    redis.call('SETBIT', bmKey, offset, 1)
    return 1
elseif op == 'remove' then
    if prev == 0 then
        return 0
    end
    redis.call('SETBIT', bmKey, offset, 0)
    return 1
end
return -1

