---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2026/3/29 下午12:27
---



-- 令牌桶限流算法脚本
-- KEYS[1]: 限流键 (例如：rl:follow:{userId})
-- ARGV[1]: 桶容量 (capacity)
-- ARGV[2]: 补充速率 (rate, 每秒补充的令牌数)

local key = KEYS[1] --redis的key
local capacity = tonumber(ARGV[1])  --100初始化令牌桶
local rate = tonumber(ARGV[2])  --拿到1个桶

-- 获取当前 Redis 服务器时间（秒级时间戳）
-- > time
--1774758806  Unix 时间戳（秒级）
--15151  微秒数
local now = redis.call('TIME')[1]

-- 从 Hash 中读取上次请求时间和当前令牌数
local last = redis.call('HGET', key, 'last') --上次请求时间
local tokens = redis.call('HGET', key, 'tokens')  --当前的令牌数

-- 如果是第一次访问，初始化令牌桶
if not last then
    last = now
    tokens = capacity
end

-- 计算经过的时间和应该补充的令牌数
local elapsed = tonumber(now) - tonumber(last)
local add = elapsed * rate

-- 更新令牌数（不超过容量上限）
tokens = math.min(capacity, tonumber(tokens) + add)

-- 如果令牌不足，返回 0（限流）
if tokens < 1 then
    redis.call('HSET', key, 'last', now)
    redis.call('HSET', key, 'tokens', tokens)
    return 0
end

-- 消耗一个令牌
tokens = tokens - 1

-- 保存新状态
redis.call('HSET', key, 'last', now)
redis.call('HSET', key, 'tokens', tokens)

-- 设置过期时间（60 秒）
redis.call('PEXPIRE', key, 60000)

-- 返回 1（允许请求）
return 1

